services:


  db:
    image: ghcr.io/baosystems/postgis:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - staybooking-pg-local:/var/lib/postgresql
    ports:
      - "5433:5433"


volumes:
  staybooking-pg-local: